# Default values for sequencer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: "astria-dev-cluster"
replicaCount: 1

cometBFTImage: "ghcr.io/astriaorg/cometbft:0.0.2"
sequencerImage: "ghcr.io/astriaorg/sequencer:0.2.0--sequencer"
sequencerRelayerImage: "ghcr.io/astriaorg/sequencer-relayer:0.4.0--sequencer-relayer"

ports:
  cometBFTP2P: 26656
  cometBFTRPC: 26657
  gossipnet: 33900
