# Default values for sequencer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: "astria-dev-cluster"
replicaCount: 1

# sequencer core images
cometBFTImage: docker.io/cometbft/cometbft:v0.37.x
sequencerImage: ghcr.io/astriaorg/sequencer:0.4.1--sequencer
sequencerRelayerImage: ghcr.io/astriaorg/sequencer-relayer:0.5.1--sequencer-relayer

# endpoint with which to access celestia network bridge node
celestiaEndpoint: http://celestia-service:26658"

# Whether to use tty readable logging for astria services, when false use json.
# Best to be false in production environments, true for clean logs on local dev.
useTTY: true

# Values for CometBFT node configuration
CometBFT:
  # CometBFT P2P Private key.
  # This is a secret key, should use a secret manager for production deployments
  privNodeKey: YWdl/6zNNNIhJX+ZCaw0dxWZ6xFunB9HEJ41bz22wvkrqDA8ls0DbwtCTBTEoM3H4ePdgq6Ha1hJonWWNpZekA==
  # Fields associated with running a validator
  privValidatorKey:
    # Ed25519 address of validator
    address: 091E47761C58C474534F4D414AF104A6CAF90C22
    # public key for the validator address
    pubKey: lV57+rGs2vac7mvkGHP1oBFGHPJM3a+WoAzeFDCJDNU=
    # private key for the validator address
    # This is a secret key, should use a secret manager for production deployments
    privKey: dGOTAweQV8Do9P2n+A8m5EnboDrlxgD3dg4vrYpdIRqVXnv6saza9pzua+QYc/WgEUYc8kzdr5agDN4UMIkM1Q==

ports:
  cometBFTP2P: 26656
  cometBFTRPC: 26657
  sequencerABCI: 26658
  relayerRPC: 2450

storage:
  sequencerSharedStorage:
    type: "local"
    size: "5Gi"
    persistentVolumeName: "sequencer-shared-storage"
    path: "/data/sequencer-data"

# Allows to override storage class for when the storage class already exists, like in GKE.
sharedStorageClassOverride: ""