# Default values for sequencer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: "astria-dev-cluster"
replicaCount: 1

# sequencer core images
cometBFTImage: docker.io/cometbft/cometbft:v0.37.x
sequencerImage: ghcr.io/astriaorg/sequencer:0.4.1--sequencer
sequencerRelayerImage: ghcr.io/astriaorg/sequencer-relayer:0.5.1--sequencer-relayer

# This account is funded on genesis and provides funds for the faucet.
# NOTE - this needs to match the faucetFundingAccount in the sequencer-faucet/values.yaml
faucetFundingAccount:
  address: a8c46f92e987492de9b10a619efd4096a0608b94
  pubKey: 3aff30d91b8853688ca2edc966ae3cfd67e3571b07e6b5f24fc18ea99d2d7122
  privKey: 96f26eb410039d6559908fd64a2d1fbf21690ec18085283754811c7fb1b5f68d3aff30d91b8853688ca2edc966ae3cfd67e3571b07e6b5f24fc18ea99d2d7122

# endpoint with which to access celestia network bridge node
celestiaEndpoint: http://celestia-service:26658"

# Whether to use tty readable logging for astria services, when false use json.
# Best to be false in production environments, true for clean logs on local dev.
useTTY: true

# Values for CometBFT node configuration
CometBFT:
  # CometBFT P2P Private key.
  # This is a secret key, should use a secret manager for production deployments
  privNodeKey: YWdl/6zNNNIhJX+ZCaw0dxWZ6xFunB9HEJ41bz22wvkrqDA8ls0DbwtCTBTEoM3H4ePdgq6Ha1hJonWWNpZekA==
  # Fields associated with running a validator
  privValidatorKey:
    # Ed25519 address of validator
    address: 091E47761C58C474534F4D414AF104A6CAF90C22
    # public key for the validator address
    pubKey: lV57+rGs2vac7mvkGHP1oBFGHPJM3a+WoAzeFDCJDNU=
    # private key for the validator address
    # This is a secret key, should use a secret manager for production deployments
    privKey: dGOTAweQV8Do9P2n+A8m5EnboDrlxgD3dg4vrYpdIRqVXnv6saza9pzua+QYc/WgEUYc8kzdr5agDN4UMIkM1Q==

ports:
  cometBFTP2P: 26656
  cometBFTRPC: 26657
  sequencerABCI: 26658
  relayerRPC: 2450

storage:
  sequencerSharedStorage:
    type: "local"
    size: "5Gi"
    persistentVolumeName: "sequencer-shared-storage"
    storageClassName: "sequencer-shared-storage-local"
    path: "/data/sequencer-data"
