apiVersion: v1
kind: ConfigMap
metadata:
  name: cometbft-config
  namespace: astria-dev-cluster
data:
  genesis.json: |
    {{- .Files.Get "files/cometbft/config/genesis.json" | nindent 4 }}
  node_key.json: |
    {{- .Files.Get "files/cometbft/config/node_key.json" | nindent 4 }}
  priv_validator_key.json: |
    {{- .Files.Get "files/cometbft/config/priv_validator_key.json" | nindent 4 }}
  config.toml: |
    {{- tpl (.Files.Get "files/cometbft/config/config.toml") $ | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cometbft-data
  namespace: astria-dev-cluster
data:
  priv_validator_state.json: |
    {{- .Files.Get "files/cometbft/data/priv_validator_state.json" | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cometbft-env
  namespace: astria-dev-cluster
data:
  COMET_BFT_RPC_PORT: "{{ .Values.ports.cometBFTRPC }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sequencer-env
  namespace: astria-dev-cluster
data:
  ASTRIA_SEQUENCER_LOG: "astria_sequencer=debug"
  ASTRIA_SEQUENCER_LISTEN_ADDR: "127.0.0.1:{{ .Values.ports.sequencerABCI }}"
  ASTRIA_SEQUENCER_DB_FILEPATH: "/sequencer/penumbra.db"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: relayer-env
  namespace: astria-dev-cluster
data:
  ASTRIA_SEQUENCER_RELAYER_LOG: "astria_sequencer_relayer=debug"
  ASTRIA_SEQUENCER_RELAYER_SEQUENCER_ENDPOINT: "http://127.0.0.1:{{ .Values.ports.cometBFTRPC }}"
  ASTRIA_SEQUENCER_RELAYER_CELESTIA_ENDPOINT: "http://celestia-service:26658"
  ASTRIA_SEQUENCER_RELAYER_GAS_LIMIT: "1000000"
  ASTRIA_SEQUENCER_RELAYER_BLOCK_TIME: "1000"
  ASTRIA_SEQUENCER_RELAYER_VALIDATOR_KEY_FILE: /cometbft/config/priv_validator_key.json
  ASTRIA_SEQUENCER_RELAYER_RPC_PORT: "{{ .Values.ports.relayerRPC }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: relayer-scripts
  namespace: astria-dev-cluster
data:
  start-relayer.sh: |
    {{- .Files.Get "files/scripts/start-relayer.sh" | nindent 4 }}
---
