{{/* We only want to create a storage class if we are local. */}}
{{/* For production, you need to create a StorageClass on GKE. */}}
{{- if .Values.storage.enabled }}
{{ range $key, $value := .Values.storage }}
{{- if eq $value.type "local" }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ $value.storageClassName }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
---
{{- end }}
{{ end }}
{{- end }}
