apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.rollupName }}-ingress
  namespace: astria-dev-cluster
spec:
  rules:
    - 
      # host: executor.{{ .Values.rollupName }}.localdev.me
      http:
        paths:
          - path: /{{ .Values.rollupName }}-executor
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.rollupName }}-evm-service
                port:
                  name: json-rpc-svc
    - 
      # host: ws-executor.{{ .Values.rollupName }}.localdev.me
      http:
        paths:
          - path: /{{ .Values.rollupName }}-ws-executor
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.rollupName }}-evm-service
                port:
                  name: ws-rpc-svc
    - 
      # host: faucet.{{ .Values.rollupName }}.localdev.me
      http:
        paths:
          - path: /{{ .Values.rollupName }}-faucet
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.rollupName }}-faucet-service
                port:
                  name: faucet-svc
    - 
      # host: blockscout.{{ .Values.rollupName }}.localdev.me
      http:
        paths:
          - path: /{{ .Values.rollupName }}-blockscout
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.rollupName }}-blockscout-svc
                port:
                  name: blockscout-svc
