apiVersion: v1
kind: ConfigMap
metadata:
  name: relayer-env
  namespace: {{ .Values.global.namespace }}
data:
  ASTRIA_SEQUENCER_RELAYER_LOG: "astria_sequencer_relayer=debug"
  ASTRIA_SEQUENCER_RELAYER_SEQUENCER_ENDPOINT: "{{ .Values.config.relayer.sequencerRpc }}"
  ASTRIA_SEQUENCER_RELAYER_CELESTIA_ENDPOINT: "{{ .Values.config.relayer.celestiaRpc }}"
  ASTRIA_SEQUENCER_RELAYER_BLOCK_TIME: "1000"
  ASTRIA_SEQUENCER_RELAYER_VALIDATOR_KEY_FILE: /cometbft/config/priv_validator_key.json
  ASTRIA_SEQUENCER_RELAYER_RPC_PORT: "{{ .Values.ports.relayerRPC }}"
  ASTRIA_SEQUENCER_RELAYER_RELAY_ONLY_VALIDATOR_KEY_BLOCKS: "false"
  ASTRIA_SEQUENCER_RELAYER_CELESTIA_BEARER_TOKEN: "{{ .Values.config.relayer.celestiaBearerToken }}"
  # false: the service will write to stdout if connected to a TTY. See `.Values.global.useTTY`
  ASTRIA_SEQUENCER_RELAYER_FORCE_STDOUT: "false"
  # false: the service will not try to connect to an OTEL endpoint.
  ASTRIA_SEQUENCER_RELAYER_NO_OTEL: "false"
  ASTRIA_SEQUENCER_RELAYER_PRETTY_PRINT: "true"
  TOKEN_SERVER: "{{ .Values.config.relayer.tokenServer }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: relayer-scripts
  namespace: {{ .Values.global.namespace }}
data:
  start-relayer.sh: |
    {{- .Files.Get "files/scripts/start-relayer.sh" | nindent 4 }}
---
