apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: astria-dev-cluster
resources:
- config-maps.yml
- deployment.yml
- service.yml
- ingress.yml
configMapGenerator:
- name: metro-scripts
  namespace: astria-dev-cluster
  files:
  - scripts/configure-metro.sh
  - scripts/init-metro.sh
  - scripts/start-metro.sh
- name: celestia-appd-scripts
  namespace: astria-dev-cluster
  files:
  - scripts/init-celestia-appd.sh
  - scripts/start-celestia-appd.sh
- name: bridge-scripts
  namespace: astria-dev-cluster
  files:
  - scripts/init-bridge.sh
  - scripts/start-bridge.sh
- name: executor-scripts
  namespace: astria-dev-cluster
  files:
  - scripts/configure-geth.sh
  - scripts/init-geth.sh
  - scripts/start-geth.sh

