kind: Service
apiVersion: v1
metadata:
  name: astria-dev-cluster-service
  namespace: astria-dev-cluster
spec:
  selector:
    app: astria-dev-cluster
  ports:
    - name: sequencer-svc
      port: 1318
      targetPort: sequencer-svc
    - name: bridge-svc
      port: 26659
      targetPort: bridge-svc
---
