{{- if .Values.ingress.enabled -}}
{{- $ingressApiIsStable := eq (include "rollup.ingress.isStable" .) "true" -}}
{{- $ingressSupportsIngressClassName := eq (include "rollup.ingress.supportsIngressClassName" .) "true" -}}
{{- $ingressSupportsPathType := eq (include "rollup.ingress.supportsPathType" .) "true" -}}
{{- $ingressPathType := .Values.ingress.pathType -}}
{{- $extraPaths := .Values.ingress.extraPaths -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.config.rollup.name }}-ingress
  namespace: {{ .Values.namespace }}
  labels:
    {{- with .Values.ingress.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ tpl $value $ | quote }}
    {{- end }}
  {{- end }}
spec:
  {{- if and $ingressSupportsIngressClassName .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  {{- end -}}
  {{- with .Values.ingress.defaultBackend }}
  defaultBackend:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  rules:
    {{- if .Values.ingress.hosts  }}
  {{- with .Values.ingress.hosts }} 
  {{- tpl (toYaml .) $ | nindent 6 }}
  {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  {{- else }}
    - host: executor.{{ .Values.config.rollup.name }}.{{ .Values.ingress.hostname }}
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.config.rollup.name }}-evm-service
                port:
                  name: json-rpc-svc
    - host: ws-executor.{{ .Values.config.rollup.name }}.{{ .Values.ingress.hostname }}
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.config.rollup.name }}-evm-service
                port:
                  name: ws-rpc-svc
    - host: faucet.{{ .Values.config.rollup.name }}.{{ .Values.ingress.hostname }}
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.config.rollup.name }}-faucet-service
                port:
                  name: faucet-svc
    - host: blockscout.{{ .Values.config.rollup.name }}.{{ .Values.ingress.hostname }}
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.config.rollup.name }}-blockscout-svc
                port:
                  name: blockscout-svc
  {{- end -}}
{{- end }}

