apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.config.rollup.name }}-celestia-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.config.rollup.name }}-astria-dev-cluster
  ports:
    - name: bridge-rest
      port: {{ .Values.ports.bridgeHTTP }}
      targetPort: bridge-rest
    - name: bridge-jsonrpc
      port: {{ .Values.ports.bridgeRPC }}
      targetPort: bridge-jsonrpc
---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.config.rollup.name }}-evm-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.config.rollup.name }}-astria-dev-cluster
  ports:
    - name: json-rpc-svc
      port: {{ .Values.ports.jsonRPC }}
      targetPort: json-rpc
    - name: ws-rpc-svc
      port: {{ .Values.ports.wsRPC }}
      targetPort: ws-rpc
    - name: gossipnet-svc
      port: {{ .Values.ports.gossipnet }}
      targetPort: gossipnet
---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.config.rollup.name }}-faucet-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.config.rollup.name }}-astria-dev-cluster
  ports:
    - name: faucet-svc
      port: {{ .Values.ports.faucet }}
      targetPort: faucet
---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.config.rollup.name }}-blockscout-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.config.rollup.name }}-astria-dev-cluster
  ports:
    - name: blockscout-svc
      port: {{ .Values.ports.blockscout }}
      targetPort: blockscout
